### ISSUE TITLE
Pack-specific sound effects 

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#1]
Two levels seem to have their sound effects broken. Possibly due to the use of `a_playSound()` instead of `a_playPackSound()`.

Levels tested:
Pac-Man from Hexadorsip 1
Reversal from Exschwasion 3

**Comment by Bauumm** [comment]
This is weird, because I store a table of all custom sounds a pack has in Lua, so if a custom sound is played I use `a_playPackSound` and otherwise I use `a_playSound`.

**Comment by Bauumm** [comment]
Ok, I think I found the culprit, in 1.92 sounds are prefixed with the pack name so `playSound("Hexadorsip_pManRight.ogg")` for example would be `playSound("pManRight.ogg")` in the new version.

**Comment by Bauumm** [comment]
This is fixed in the newest commit in the `source_modify` branch
