### ISSUE TITLE
[IDFK] Multiple Choice

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#13]
Multiple choice from IDFK spawns some blocking walls that encourage you to swap, but in the ported version, those walls are stuttery and can be passed straight through.

**Comment by Bauumm** [comment]
Oh this is due to an optimization where I don't process collisions for stopped wallAccs, should be fixed easily by just not counting them as stopped if within player range.

**Comment by Bauumm** [comment]
Should be fixed in the newest version.
