### ISSUE TITLE
Reversal's fastspin(?) not working right

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#2]
The third level of Exschwasion 3, Reversal, had a [fast spin effect at the increments](https://youtu.be/B1iWav-pbqY?t=18), but it looks a lot different in the port. It doesn't seem to be manually-controlled, based on the 1.92 files, so there's something else funny going on.

**Comment by Bauumm** [comment]
I currently implement the whole increment system in Lua for 1.92 parity (because 1.92 cuts off patterns and the steam versions system doesn't work with custom walls). So it's probably a bug in there.

**Comment by Bauumm** [comment]
Ok, so this was because I did not multiply the fast spin with the sign, so depending on what direction the level was rotating in fast spin could work against it.
It should be fixed with the newest commit in the source_modify branch now.
