### ISSUE TITLE
IDFK

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#3]
The entire pack "Ideal Definition of Face Knocker" does not have a single playable level in the port (and the styles are identical between levels). Granted, I can't playtest the 1.92 version due to my exe not opening, but I don't recall that being the case before. It seems to be from a music-ID related error.

**Comment by Bauumm** [comment]
Oh I remember I had issues converting it already because it used funny characters in file names, might be related.

**Comment by Bauumm** [comment]
I can't seem to reproduce this issue, there are a bit of errors in some of the levels but most are playable for me.

**Comment by vindowvipre** [comment]
Ok, I guess I'll mark this as completed since the original error was non reproducible. And I'll make some new issues
