### ISSUE TITLE
[MY] Construction

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#5]
The third level of Modern Year, Construction, has slightly misaligned accelerating walls that don't make a smooth barrage shape. I _think_ they didn't do that in 1.92, but no videos exist, so this might be a non-issue.

**Comment by Bauumm** [comment]
This seems to actually be an issue, I just have no idea what is causing it.

**Comment by Bauumm** [comment]
Ok, turns out this happens in 1.92 too. Just way less noticable due to the framerate, so if I set the framerate of this level really high this seems to look the same as 1.92.
