### ISSUE TITLE
[MY] 404

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#6]
The 6th level of Modern Year, 404, has a broken style. [This](https://www.youtube.com/watch?v=VBN0hpVy_Ys) is what it normally looks like, with no pink at all. I think this applies to the next level, Dead Pixel, as well.

**Comment by Bauumm** [comment]
This is an issue with Hue getting outside of the normal 0..360 range.

**Comment by vindowvipre** [comment]
Gameplay colors look great now, but the menu doesn't. Probably not worth considering the menu for future converter updates.
